services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:rw
  cvat_worker_default:
    volumes:
      - cvat_share:/home/django/share:rw

volumes:
  cvat_share:
    driver_opts:
      type: none
      o: bind,file_mode=0777,dir_mode=0777
      device: /volume1/cvat
