services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_default:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.50.224,rw"
      device: ":/LabData/manual_annotation"
