services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_default:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: cifs
      o: addr=127.0.0.1,username=cvat,password=cvat,file_mode=0777,dir_mode=0777
      device: //127.0.0.1/cvat
